"""initial migration

Revision ID: 657fd146d6ab
Revises: 
Create Date: 2026-08-20 12:34:53.978320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '657fd146d6ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_created_at'), 'tenants', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenants_created_by'), 'tenants', ['created_by'], unique=False)
    op.create_index(op.f('ix_tenants_description'), 'tenants', ['description'], unique=False)
    op.create_index(op.f('ix_tenants_is_global'), 'tenants', ['is_global'], unique=False)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sso_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_key_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.create_index(op.f('ix_users_sso_id'), 'users', ['sso_id'], unique=True)
    op.create_table('knowledge_spaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_spaces_created_at'), 'knowledge_spaces', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_spaces_created_by'), 'knowledge_spaces', ['created_by'], unique=False)
    op.create_index(op.f('ix_knowledge_spaces_description'), 'knowledge_spaces', ['description'], unique=False)
    op.create_index(op.f('ix_knowledge_spaces_name'), 'knowledge_spaces', ['name'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_space_id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_space_id'], ['knowledge_spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_created_by'), 'documents', ['created_by'], unique=False)
    op.create_index(op.f('ix_documents_description'), 'documents', ['description'], unique=False)
    op.create_index(op.f('ix_documents_knowledge_space_id'), 'documents', ['knowledge_space_id'], unique=False)
    op.create_table('documents_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'ACTIVE', 'FAILED', 'ARCHIVED', name='documentversionstatus', native_enum=False), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_versions_document_id'), 'documents_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_documents_versions_task_id'), 'documents_versions', ['task_id'], unique=False)
    op.create_index(op.f('ix_documents_versions_version_number'), 'documents_versions', ['version_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_versions_version_number'), table_name='documents_versions')
    op.drop_index(op.f('ix_documents_versions_task_id'), table_name='documents_versions')
    op.drop_index(op.f('ix_documents_versions_document_id'), table_name='documents_versions')
    op.drop_table('documents_versions')
    op.drop_index(op.f('ix_documents_knowledge_space_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_description'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_by'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_knowledge_spaces_name'), table_name='knowledge_spaces')
    op.drop_index(op.f('ix_knowledge_spaces_description'), table_name='knowledge_spaces')
    op.drop_index(op.f('ix_knowledge_spaces_created_by'), table_name='knowledge_spaces')
    op.drop_index(op.f('ix_knowledge_spaces_created_at'), table_name='knowledge_spaces')
    op.drop_table('knowledge_spaces')
    op.drop_index(op.f('ix_users_sso_id'), table_name='users')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_is_global'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_description'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_created_by'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_created_at'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
